language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r preamble.txt
  - pip install -r requirements.txt
  - pip install -r denouement.txt
# command to run tests
script: 
  - py.test ./test_module/test_analyze.py -v
  - py.test ./test_module/test_utils.py -v
  - py.test ./test_module/test_construct_portfolio.py -v
