language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r preamble.txt
  - pip install -r requirements.txt
# command to run tests
script: cd visualize_wealth; python -m doctest analyze.py; python -m doctest construct_portfolio.py;
